#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_PosingSpy_Weapon_Xiu_Mod2_3p

#include "Basic.hpp"

#include "ABP_PosingSpy_Weapon_Xiu_Mod2_3p_classes.hpp"
#include "ABP_PosingSpy_Weapon_Xiu_Mod2_3p_parameters.hpp"


namespace SDK
{

// Function ABP_PosingSpy_Weapon_Xiu_Mod2_3p.ABP_PosingSpy_Weapon_Xiu_Mod2_3p_C.ExecuteUbergraph_ABP_PosingSpy_Weapon_Xiu_Mod2_3p
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_PosingSpy_Weapon_Xiu_Mod2_3p_C::ExecuteUbergraph_ABP_PosingSpy_Weapon_Xiu_Mod2_3p(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PosingSpy_Weapon_Xiu_Mod2_3p_C", "ExecuteUbergraph_ABP_PosingSpy_Weapon_Xiu_Mod2_3p");

	Params::ABP_PosingSpy_Weapon_Xiu_Mod2_3p_C_ExecuteUbergraph_ABP_PosingSpy_Weapon_Xiu_Mod2_3p Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_PosingSpy_Weapon_Xiu_Mod2_3p.ABP_PosingSpy_Weapon_Xiu_Mod2_3p_C.OnSpyToolEvent_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ESpyToolEvent                           EventType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABaseSpyTool*                     SpyTool                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_PosingSpy_Weapon_Xiu_Mod2_3p_C::OnSpyToolEvent_Event_0(ESpyToolEvent EventType, class ABaseSpyTool* SpyTool)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PosingSpy_Weapon_Xiu_Mod2_3p_C", "OnSpyToolEvent_Event_0");

	Params::ABP_PosingSpy_Weapon_Xiu_Mod2_3p_C_OnSpyToolEvent_Event_0 Parms{};

	Parms.EventType = EventType;
	Parms.SpyTool = SpyTool;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_PosingSpy_Weapon_Xiu_Mod2_3p.ABP_PosingSpy_Weapon_Xiu_Mod2_3p_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UABP_PosingSpy_Weapon_Xiu_Mod2_3p_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PosingSpy_Weapon_Xiu_Mod2_3p_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_PosingSpy_Weapon_Xiu_Mod2_3p.ABP_PosingSpy_Weapon_Xiu_Mod2_3p_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_PosingSpy_Weapon_Xiu_Mod2_3p_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PosingSpy_Weapon_Xiu_Mod2_3p_C", "AnimGraph");

	Params::ABP_PosingSpy_Weapon_Xiu_Mod2_3p_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

