#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Briefcase

#include "Basic.hpp"

#include "BP_Briefcase_classes.hpp"
#include "BP_Briefcase_parameters.hpp"


namespace SDK
{

// Function BP_Briefcase.BP_Briefcase_C.ExecuteUbergraph_BP_Briefcase
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Briefcase_C::ExecuteUbergraph_BP_Briefcase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Briefcase_C", "ExecuteUbergraph_BP_Briefcase");

	Params::BP_Briefcase_C_ExecuteUbergraph_BP_Briefcase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Briefcase.BP_Briefcase_C.BP_OnHiddenInContainerChange
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bNowHidden                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Briefcase_C::BP_OnHiddenInContainerChange(bool bNowHidden)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Briefcase_C", "BP_OnHiddenInContainerChange");

	Params::BP_Briefcase_C_BP_OnHiddenInContainerChange Parms{};

	Parms.bNowHidden = bNowHidden;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Briefcase.BP_Briefcase_C.BndEvt__BP_Briefcase_InteractableComp_K2Node_ComponentBoundEvent_1_OnInteractionDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UInteracterComponent*             Interacter                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInteractableComponent*           Interactable                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Briefcase_C::BndEvt__BP_Briefcase_InteractableComp_K2Node_ComponentBoundEvent_1_OnInteractionDelegate__DelegateSignature(class UInteracterComponent* Interacter, class UInteractableComponent* Interactable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Briefcase_C", "BndEvt__BP_Briefcase_InteractableComp_K2Node_ComponentBoundEvent_1_OnInteractionDelegate__DelegateSignature");

	Params::BP_Briefcase_C_BndEvt__BP_Briefcase_InteractableComp_K2Node_ComponentBoundEvent_1_OnInteractionDelegate__DelegateSignature Parms{};

	Parms.Interacter = Interacter;
	Parms.Interactable = Interactable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Briefcase.BP_Briefcase_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Briefcase_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Briefcase_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Briefcase.BP_Briefcase_C.BndEvt__InteractableComp_K2Node_ComponentBoundEvent_0_OnInteractionDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UInteracterComponent*             Interacter                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInteractableComponent*           Interactable                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Briefcase_C::BndEvt__InteractableComp_K2Node_ComponentBoundEvent_0_OnInteractionDelegate__DelegateSignature(class UInteracterComponent* Interacter, class UInteractableComponent* Interactable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Briefcase_C", "BndEvt__InteractableComp_K2Node_ComponentBoundEvent_0_OnInteractionDelegate__DelegateSignature");

	Params::BP_Briefcase_C_BndEvt__InteractableComp_K2Node_ComponentBoundEvent_0_OnInteractionDelegate__DelegateSignature Parms{};

	Parms.Interacter = Interacter;
	Parms.Interactable = Interactable;

	UObject::ProcessEvent(Func, &Parms);
}

}

