#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BasePickableActor

#include "Basic.hpp"

#include "BP_BasePickableActor_classes.hpp"
#include "BP_BasePickableActor_parameters.hpp"


namespace SDK
{

// Function BP_BasePickableActor.BP_BasePickableActor_C.ExecuteUbergraph_BP_BasePickableActor
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BasePickableActor_C::ExecuteUbergraph_BP_BasePickableActor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BasePickableActor_C", "ExecuteUbergraph_BP_BasePickableActor");

	Params::BP_BasePickableActor_C_ExecuteUbergraph_BP_BasePickableActor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BasePickableActor.BP_BasePickableActor_C.OnInteractionIconStateChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EInteractionIconState                   NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EInteractionIconState                   OldState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BasePickableActor_C::OnInteractionIconStateChanged(EInteractionIconState NewState, EInteractionIconState OldState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BasePickableActor_C", "OnInteractionIconStateChanged");

	Params::BP_BasePickableActor_C_OnInteractionIconStateChanged Parms{};

	Parms.NewState = NewState;
	Parms.OldState = OldState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BasePickableActor.BP_BasePickableActor_C.BndEvt__BP_BaseIntelActor_InteractableComp_K2Node_ComponentBoundEvent_3_OnInteractionIconChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UInteractionIconComponent*        OldIcon                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInteractionIconComponent*        NewIcon                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BasePickableActor_C::BndEvt__BP_BaseIntelActor_InteractableComp_K2Node_ComponentBoundEvent_3_OnInteractionIconChanged__DelegateSignature(class UInteractionIconComponent* OldIcon, class UInteractionIconComponent* NewIcon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BasePickableActor_C", "BndEvt__BP_BaseIntelActor_InteractableComp_K2Node_ComponentBoundEvent_3_OnInteractionIconChanged__DelegateSignature");

	Params::BP_BasePickableActor_C_BndEvt__BP_BaseIntelActor_InteractableComp_K2Node_ComponentBoundEvent_3_OnInteractionIconChanged__DelegateSignature Parms{};

	Parms.OldIcon = OldIcon;
	Parms.NewIcon = NewIcon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BasePickableActor.BP_BasePickableActor_C.BP_OnHiddenInContainerChange
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bNowHidden                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BasePickableActor_C::BP_OnHiddenInContainerChange(bool bNowHidden)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BasePickableActor_C", "BP_OnHiddenInContainerChange");

	Params::BP_BasePickableActor_C_BP_OnHiddenInContainerChange Parms{};

	Parms.bNowHidden = bNowHidden;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BasePickableActor.BP_BasePickableActor_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_BasePickableActor_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BasePickableActor_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

