#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BasePowerup

#include "Basic.hpp"

#include "BP_BasePowerup_classes.hpp"
#include "BP_BasePowerup_parameters.hpp"


namespace SDK
{

// Function BP_BasePowerup.BP_BasePowerup_C.ExecuteUbergraph_BP_BasePowerup
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BasePowerup_C::ExecuteUbergraph_BP_BasePowerup(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BasePowerup_C", "ExecuteUbergraph_BP_BasePowerup");

	Params::BP_BasePowerup_C_ExecuteUbergraph_BP_BasePowerup Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BasePowerup.BP_BasePowerup_C.OnNewSpySpawnedEvent_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ADeceiveIncPlayerController*      PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ASpy*                             Spy                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BasePowerup_C::OnNewSpySpawnedEvent_Event_0(class ADeceiveIncPlayerController* PlayerController, class ASpy* Spy)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BasePowerup_C", "OnNewSpySpawnedEvent_Event_0");

	Params::BP_BasePowerup_C_OnNewSpySpawnedEvent_Event_0 Parms{};

	Parms.PlayerController = PlayerController;
	Parms.Spy = Spy;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BasePowerup.BP_BasePowerup_C.SetupPowerup
// (BlueprintCallable, BlueprintEvent)

void ABP_BasePowerup_C::SetupPowerup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BasePowerup_C", "SetupPowerup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BasePowerup.BP_BasePowerup_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_BasePowerup_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BasePowerup_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BasePowerup.BP_BasePowerup_C.OnInteractionIconStateChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EInteractionIconState                   NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EInteractionIconState                   OldState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BasePowerup_C::OnInteractionIconStateChanged(EInteractionIconState NewState, EInteractionIconState OldState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BasePowerup_C", "OnInteractionIconStateChanged");

	Params::BP_BasePowerup_C_OnInteractionIconStateChanged Parms{};

	Parms.NewState = NewState;
	Parms.OldState = OldState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BasePowerup.BP_BasePowerup_C.BndEvt__BP_BaseIntelActor_InteractableComp_K2Node_ComponentBoundEvent_3_OnInteractionIconChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UInteractionIconComponent*        OldIcon                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInteractionIconComponent*        NewIcon                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BasePowerup_C::BndEvt__BP_BaseIntelActor_InteractableComp_K2Node_ComponentBoundEvent_3_OnInteractionIconChanged__DelegateSignature(class UInteractionIconComponent* OldIcon, class UInteractionIconComponent* NewIcon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BasePowerup_C", "BndEvt__BP_BaseIntelActor_InteractableComp_K2Node_ComponentBoundEvent_3_OnInteractionIconChanged__DelegateSignature");

	Params::BP_BasePowerup_C_BndEvt__BP_BaseIntelActor_InteractableComp_K2Node_ComponentBoundEvent_3_OnInteractionIconChanged__DelegateSignature Parms{};

	Parms.OldIcon = OldIcon;
	Parms.NewIcon = NewIcon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BasePowerup.BP_BasePowerup_C.BndEvt__InteractableComp_K2Node_ComponentBoundEvent_0_OnInteractionDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UInteracterComponent*             Interacter                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInteractableComponent*           Interactable                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BasePowerup_C::BndEvt__InteractableComp_K2Node_ComponentBoundEvent_0_OnInteractionDelegate__DelegateSignature(class UInteracterComponent* Interacter, class UInteractableComponent* Interactable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BasePowerup_C", "BndEvt__InteractableComp_K2Node_ComponentBoundEvent_0_OnInteractionDelegate__DelegateSignature");

	Params::BP_BasePowerup_C_BndEvt__InteractableComp_K2Node_ComponentBoundEvent_0_OnInteractionDelegate__DelegateSignature Parms{};

	Parms.Interacter = Interacter;
	Parms.Interactable = Interactable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BasePowerup.BP_BasePowerup_C.BP_OnHiddenInContainerChange
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bNowHidden                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BasePowerup_C::BP_OnHiddenInContainerChange(bool bNowHidden)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BasePowerup_C", "BP_OnHiddenInContainerChange");

	Params::BP_BasePowerup_C_BP_OnHiddenInContainerChange Parms{};

	Parms.bNowHidden = bNowHidden;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BasePowerup.BP_BasePowerup_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_BasePowerup_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BasePowerup_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

