#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DeceiveIncMenuGameModeBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DeceiveInc_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DeceiveIncMenuGameModeBase.BP_DeceiveIncMenuGameModeBase_C
// 0x0010 (0x02D0 - 0x02C0)
class ABP_DeceiveIncMenuGameModeBase_C final : public ADeceiveIncMenuGameModeBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_DeceiveIncMenuGameModeBase(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DeceiveIncMenuGameModeBase_C">();
	}
	static class ABP_DeceiveIncMenuGameModeBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DeceiveIncMenuGameModeBase_C>();
	}
};
static_assert(alignof(ABP_DeceiveIncMenuGameModeBase_C) == 0x000008, "Wrong alignment on ABP_DeceiveIncMenuGameModeBase_C");
static_assert(sizeof(ABP_DeceiveIncMenuGameModeBase_C) == 0x0002D0, "Wrong size on ABP_DeceiveIncMenuGameModeBase_C");
static_assert(offsetof(ABP_DeceiveIncMenuGameModeBase_C, UberGraphFrame) == 0x0002C0, "Member 'ABP_DeceiveIncMenuGameModeBase_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_DeceiveIncMenuGameModeBase_C, DefaultSceneRoot) == 0x0002C8, "Member 'ABP_DeceiveIncMenuGameModeBase_C::DefaultSceneRoot' has a wrong offset!");

}

