#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Display_Powerup_Guard

#include "Basic.hpp"

#include "BP_Display_Powerup_Civilian_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Display_Powerup_Guard.BP_Display_Powerup_Guard_C
// 0x0000 (0x0250 - 0x0250)
class ABP_Display_Powerup_Guard_C final : public ABP_Display_Powerup_Civilian_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Display_Powerup_Guard_C">();
	}
	static class ABP_Display_Powerup_Guard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Display_Powerup_Guard_C>();
	}
};
static_assert(alignof(ABP_Display_Powerup_Guard_C) == 0x000008, "Wrong alignment on ABP_Display_Powerup_Guard_C");
static_assert(sizeof(ABP_Display_Powerup_Guard_C) == 0x000250, "Wrong size on ABP_Display_Powerup_Guard_C");

}

