#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DeceiveIncMenuGameModeBase

#include "Basic.hpp"

#include "BP_DeceiveIncMenuGameModeBase_classes.hpp"
#include "BP_DeceiveIncMenuGameModeBase_parameters.hpp"


namespace SDK
{

// Function BP_DeceiveIncMenuGameModeBase.BP_DeceiveIncMenuGameModeBase_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_DeceiveIncMenuGameModeBase_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeceiveIncMenuGameModeBase_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DeceiveIncMenuGameModeBase.BP_DeceiveIncMenuGameModeBase_C.ExecuteUbergraph_BP_DeceiveIncMenuGameModeBase
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DeceiveIncMenuGameModeBase_C::ExecuteUbergraph_BP_DeceiveIncMenuGameModeBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeceiveIncMenuGameModeBase_C", "ExecuteUbergraph_BP_DeceiveIncMenuGameModeBase");

	Params::BP_DeceiveIncMenuGameModeBase_C_ExecuteUbergraph_BP_DeceiveIncMenuGameModeBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

