#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HealingConsumable

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_BasePickableActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_HealingConsumable.BP_HealingConsumable_C
// 0x0010 (0x0338 - 0x0328)
class ABP_HealingConsumable_C : public ABP_BasePickableActor_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_HealingConsumable_C;             // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UMaxResourceConditionComponent*         MaxResourceCondition;                              // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_HealingConsumable(int32 EntryPoint);
	void BndEvt__BP_FoodBase_InteractableComp_K2Node_ComponentBoundEvent_1_OnInteractionDelegate__DelegateSignature(class UInteracterComponent* Interacter, class UInteractableComponent* Interactable);
	void BndEvt__BP_FoodBase_InteractableComp_K2Node_ComponentBoundEvent_0_OnInteractionDelegate__DelegateSignature(class UInteracterComponent* Interacter, class UInteractableComponent* Interactable);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_HealingConsumable_C">();
	}
	static class ABP_HealingConsumable_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_HealingConsumable_C>();
	}
};
static_assert(alignof(ABP_HealingConsumable_C) == 0x000008, "Wrong alignment on ABP_HealingConsumable_C");
static_assert(sizeof(ABP_HealingConsumable_C) == 0x000338, "Wrong size on ABP_HealingConsumable_C");
static_assert(offsetof(ABP_HealingConsumable_C, UberGraphFrame_BP_HealingConsumable_C) == 0x000328, "Member 'ABP_HealingConsumable_C::UberGraphFrame_BP_HealingConsumable_C' has a wrong offset!");
static_assert(offsetof(ABP_HealingConsumable_C, MaxResourceCondition) == 0x000330, "Member 'ABP_HealingConsumable_C::MaxResourceCondition' has a wrong offset!");

}

