#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InputModifier_Accelerator_Horiz

#include "Basic.hpp"

#include "DeceiveInc_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_InputModifier_Accelerator_Horiz.BP_InputModifier_Accelerator_Horiz_C
// 0x0000 (0x0048 - 0x0048)
class UBP_InputModifier_Accelerator_Horiz_C final : public USweetInputModifierAccelerators
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_InputModifier_Accelerator_Horiz_C">();
	}
	static class UBP_InputModifier_Accelerator_Horiz_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_InputModifier_Accelerator_Horiz_C>();
	}
};
static_assert(alignof(UBP_InputModifier_Accelerator_Horiz_C) == 0x000008, "Wrong alignment on UBP_InputModifier_Accelerator_Horiz_C");
static_assert(sizeof(UBP_InputModifier_Accelerator_Horiz_C) == 0x000048, "Wrong size on UBP_InputModifier_Accelerator_Horiz_C");

}

