#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InputModifierAimAssist2D

#include "Basic.hpp"

#include "DeceiveInc_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_InputModifierAimAssist2D.BP_InputModifierAimAssist2D_C
// 0x0000 (0x0038 - 0x0038)
class UBP_InputModifierAimAssist2D_C final : public USweetAimAssistInputModifier2D
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_InputModifierAimAssist2D_C">();
	}
	static class UBP_InputModifierAimAssist2D_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_InputModifierAimAssist2D_C>();
	}
};
static_assert(alignof(UBP_InputModifierAimAssist2D_C) == 0x000008, "Wrong alignment on UBP_InputModifierAimAssist2D_C");
static_assert(sizeof(UBP_InputModifierAimAssist2D_C) == 0x000038, "Wrong size on UBP_InputModifierAimAssist2D_C");

}

