#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Keycard_Orange

#include "Basic.hpp"

#include "BP_Keycard_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Keycard_Orange.BP_Keycard_Orange_C
// 0x0000 (0x0348 - 0x0348)
class ABP_Keycard_Orange_C : public ABP_Keycard_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Keycard_Orange_C">();
	}
	static class ABP_Keycard_Orange_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Keycard_Orange_C>();
	}
};
static_assert(alignof(ABP_Keycard_Orange_C) == 0x000008, "Wrong alignment on ABP_Keycard_Orange_C");
static_assert(sizeof(ABP_Keycard_Orange_C) == 0x000348, "Wrong size on ABP_Keycard_Orange_C");

}

