#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Powerup_Level_Civilian

#include "Basic.hpp"

#include "BP_BasePowerup_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Powerup_Level_Civilian.BP_Powerup_Level_Civilian_C
// 0x0000 (0x0340 - 0x0340)
class ABP_Powerup_Level_Civilian_C : public ABP_BasePowerup_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Powerup_Level_Civilian_C">();
	}
	static class ABP_Powerup_Level_Civilian_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Powerup_Level_Civilian_C>();
	}
};
static_assert(alignof(ABP_Powerup_Level_Civilian_C) == 0x000008, "Wrong alignment on ABP_Powerup_Level_Civilian_C");
static_assert(sizeof(ABP_Powerup_Level_Civilian_C) == 0x000340, "Wrong size on ABP_Powerup_Level_Civilian_C");

}

