#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VictimEffect_SocialBattery

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DeceiveInc_structs.hpp"
#include "DeceiveInc_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_VictimEffect_SocialBattery.BP_VictimEffect_SocialBattery_C
// 0x0010 (0x0468 - 0x0458)
class ABP_VictimEffect_SocialBattery_C final : public AVictimEffect
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0458(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_VictimEffect_SocialBattery(int32 EntryPoint);
	void BP_OnEffectStart(class AVictimEffect* Effect, class AActor* Victim);
	void BP_InitializeTickEffect(class UVictimEffectTickBehavior* TickEffect);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_VictimEffect_SocialBattery_C">();
	}
	static class ABP_VictimEffect_SocialBattery_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_VictimEffect_SocialBattery_C>();
	}
};
static_assert(alignof(ABP_VictimEffect_SocialBattery_C) == 0x000008, "Wrong alignment on ABP_VictimEffect_SocialBattery_C");
static_assert(sizeof(ABP_VictimEffect_SocialBattery_C) == 0x000468, "Wrong size on ABP_VictimEffect_SocialBattery_C");
static_assert(offsetof(ABP_VictimEffect_SocialBattery_C, UberGraphFrame) == 0x000458, "Member 'ABP_VictimEffect_SocialBattery_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_VictimEffect_SocialBattery_C, DefaultSceneRoot) == 0x000460, "Member 'ABP_VictimEffect_SocialBattery_C::DefaultSceneRoot' has a wrong offset!");

}

