#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFunctionLibrary_ObjectHighlight

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "DeceiveInc_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPFunctionLibrary_ObjectHighlight.BPFunctionLibrary_ObjectHighlight_C
// 0x0000 (0x0028 - 0x0028)
class UBPFunctionLibrary_ObjectHighlight_C final : public UBlueprintFunctionLibrary
{
public:
	static void BPLibrary_ObjectHighlight(class UPrimitiveComponent* HighlightedMesh, EInteractionIconState NewStateEnum, EInteractionIconState OldStateEnum, class UNiagaraComponent* FXOutline, class UObject* __WorldContext);
	static void BPLibrary_ObjectHighlightFXSetup(class UPrimitiveComponent* Mesh, class UNiagaraComponent* FX, class UObject* __WorldContext);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPFunctionLibrary_ObjectHighlight_C">();
	}
	static class UBPFunctionLibrary_ObjectHighlight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPFunctionLibrary_ObjectHighlight_C>();
	}
};
static_assert(alignof(UBPFunctionLibrary_ObjectHighlight_C) == 0x000008, "Wrong alignment on UBPFunctionLibrary_ObjectHighlight_C");
static_assert(sizeof(UBPFunctionLibrary_ObjectHighlight_C) == 0x000028, "Wrong size on UBPFunctionLibrary_ObjectHighlight_C");

}

