#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Cursor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Cursor.Cursor_C
// 0x0010 (0x0270 - 0x0260)
class UCursor_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetSwitcher*                        WidgetSwitcher_0;                                  // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Cursor(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Cursor_C">();
	}
	static class UCursor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCursor_C>();
	}
};
static_assert(alignof(UCursor_C) == 0x000008, "Wrong alignment on UCursor_C");
static_assert(sizeof(UCursor_C) == 0x000270, "Wrong size on UCursor_C");
static_assert(offsetof(UCursor_C, UberGraphFrame) == 0x000260, "Member 'UCursor_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UCursor_C, WidgetSwitcher_0) == 0x000268, "Member 'UCursor_C::WidgetSwitcher_0' has a wrong offset!");

}

