#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Enum_Spy_HealthPool

#include "Basic.hpp"


namespace SDK
{

// Enum Enum_Spy_HealthPool.Enum_Spy_HealthPool
// NumValues: 0x0004
enum class Enum_Spy_HealthPool : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	Enum_Spy_MAX                             = 3,
};

}

