#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUD_PP_Base

#include "Basic.hpp"

#include "HUD_PP_Base_classes.hpp"
#include "HUD_PP_Base_parameters.hpp"


namespace SDK
{

// Function HUD_PP_Base.HUD_PP_Base_C.ExecuteUbergraph_HUD_PP_Base
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHUD_PP_Base_C::ExecuteUbergraph_HUD_PP_Base(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_PP_Base_C", "ExecuteUbergraph_HUD_PP_Base");

	Params::HUD_PP_Base_C_ExecuteUbergraph_HUD_PP_Base Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUD_PP_Base.HUD_PP_Base_C.SetPPTexture
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       NewPPTexture                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHUD_PP_Base_C::SetPPTexture(class UTexture2D* NewPPTexture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_PP_Base_C", "SetPPTexture");

	Params::HUD_PP_Base_C_SetPPTexture Parms{};

	Parms.NewPPTexture = NewPPTexture;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUD_PP_Base.HUD_PP_Base_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHUD_PP_Base_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_PP_Base_C", "Tick");

	Params::HUD_PP_Base_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUD_PP_Base.HUD_PP_Base_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHUD_PP_Base_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_PP_Base_C", "PreConstruct");

	Params::HUD_PP_Base_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUD_PP_Base.HUD_PP_Base_C.GetDistanceInM
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Distance                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHUD_PP_Base_C::GetDistanceInM(int32* Distance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_PP_Base_C", "GetDistanceInM");

	Params::HUD_PP_Base_C_GetDistanceInM Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Distance != nullptr)
		*Distance = Parms.Distance;
}

}

