#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUD_Player_VoicechatV2_Master

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DeceiveInc_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass HUD_Player_VoicechatV2_Master.HUD_Player_VoicechatV2_Master_C
// 0x0010 (0x0290 - 0x0280)
class UHUD_Player_VoicechatV2_Master_C final : public UVoicechatMemberContainerWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UVerticalBox*                           VerticalBox_VCUsers;                               // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_HUD_Player_VoicechatV2_Master(int32 EntryPoint);
	void OnBlueprintEbusStringEvent_Event_0(const class FString& StringEvent);
	void Construct();
	void FreeSlotForMemberWidget(class UVoicechatMemberWidget* MemberWidget);
	void ReserveSlotForMemberWidget(class UVoicechatMemberWidget* MemberWidget);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HUD_Player_VoicechatV2_Master_C">();
	}
	static class UHUD_Player_VoicechatV2_Master_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHUD_Player_VoicechatV2_Master_C>();
	}
};
static_assert(alignof(UHUD_Player_VoicechatV2_Master_C) == 0x000008, "Wrong alignment on UHUD_Player_VoicechatV2_Master_C");
static_assert(sizeof(UHUD_Player_VoicechatV2_Master_C) == 0x000290, "Wrong size on UHUD_Player_VoicechatV2_Master_C");
static_assert(offsetof(UHUD_Player_VoicechatV2_Master_C, UberGraphFrame) == 0x000280, "Member 'UHUD_Player_VoicechatV2_Master_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UHUD_Player_VoicechatV2_Master_C, VerticalBox_VCUsers) == 0x000288, "Member 'UHUD_Player_VoicechatV2_Master_C::VerticalBox_VCUsers' has a wrong offset!");

}

