#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MENU_ShaderPrecompile

#include "Basic.hpp"

#include "MENU_ShaderPrecompile_classes.hpp"
#include "MENU_ShaderPrecompile_parameters.hpp"


namespace SDK
{

// Function MENU_ShaderPrecompile.MENU_ShaderPrecompile_C.GetText_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMENU_ShaderPrecompile_C::GetText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MENU_ShaderPrecompile_C", "GetText_0");

	Params::MENU_ShaderPrecompile_C_GetText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MENU_ShaderPrecompile.MENU_ShaderPrecompile_C.GetPercent_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UMENU_ShaderPrecompile_C::GetPercent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MENU_ShaderPrecompile_C", "GetPercent_0");

	Params::MENU_ShaderPrecompile_C_GetPercent_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

