#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OnlineSubsystemAccelByte

#include "Basic.hpp"

#include "PacketHandler_classes.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class OnlineSubsystemAccelByte.AuthHandlerComponentAccelByteFactory
// 0x0000 (0x0028 - 0x0028)
class UAuthHandlerComponentAccelByteFactory final : public UHandlerComponentFactory
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AuthHandlerComponentAccelByteFactory">();
	}
	static class UAuthHandlerComponentAccelByteFactory* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAuthHandlerComponentAccelByteFactory>();
	}
};
static_assert(alignof(UAuthHandlerComponentAccelByteFactory) == 0x000008, "Wrong alignment on UAuthHandlerComponentAccelByteFactory");
static_assert(sizeof(UAuthHandlerComponentAccelByteFactory) == 0x000028, "Wrong size on UAuthHandlerComponentAccelByteFactory");

// Class OnlineSubsystemAccelByte.OnlineSubsystemAccelByteUtils
// 0x0000 (0x0028 - 0x0028)
class UOnlineSubsystemAccelByteUtils final : public UBlueprintFunctionLibrary
{
public:
	static bool IsPlayerOnSamePlatform(const class FString& UniqueIdString);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"OnlineSubsystemAccelByteUtils">();
	}
	static class UOnlineSubsystemAccelByteUtils* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOnlineSubsystemAccelByteUtils>();
	}
};
static_assert(alignof(UOnlineSubsystemAccelByteUtils) == 0x000008, "Wrong alignment on UOnlineSubsystemAccelByteUtils");
static_assert(sizeof(UOnlineSubsystemAccelByteUtils) == 0x000028, "Wrong size on UOnlineSubsystemAccelByteUtils");

}

