#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Struct_SpyShared_HealthPool_SpyList

#include "Basic.hpp"

#include "Enum_Spy_HealthPool_structs.hpp"


namespace SDK
{

// ScriptStruct Struct_SpyShared_HealthPool_SpyList.Struct_SpyShared_HealthPool_SpyList
// 0x0001 (0x0001 - 0x0000)
struct FStruct_SpyShared_HealthPool_SpyList final
{
public:
	Enum_Spy_HealthPool                           HealthPoolToUse_2_114AA5034F9EE9EB6B0F2B8C88BEFF2F; // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FStruct_SpyShared_HealthPool_SpyList) == 0x000001, "Wrong alignment on FStruct_SpyShared_HealthPool_SpyList");
static_assert(sizeof(FStruct_SpyShared_HealthPool_SpyList) == 0x000001, "Wrong size on FStruct_SpyShared_HealthPool_SpyList");
static_assert(offsetof(FStruct_SpyShared_HealthPool_SpyList, HealthPoolToUse_2_114AA5034F9EE9EB6B0F2B8C88BEFF2F) == 0x000000, "Member 'FStruct_SpyShared_HealthPool_SpyList::HealthPoolToUse_2_114AA5034F9EE9EB6B0F2B8C88BEFF2F' has a wrong offset!");

}

