#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Struct_Ace_Passives_ChargeTime

#include "Basic.hpp"


namespace SDK
{

// ScriptStruct Struct_Ace_Passives_ChargeTime.Struct_Ace_Passives_ChargeTime
// 0x0008 (0x0008 - 0x0000)
struct FStruct_Ace_Passives_ChargeTime final
{
public:
	float                                         ChargeTime_3_1FEB8B4040897739BAF5EBB2C45145E9;     // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ChargeDelay_6_5291777445E7D187DF9DE789A447A243;    // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FStruct_Ace_Passives_ChargeTime) == 0x000004, "Wrong alignment on FStruct_Ace_Passives_ChargeTime");
static_assert(sizeof(FStruct_Ace_Passives_ChargeTime) == 0x000008, "Wrong size on FStruct_Ace_Passives_ChargeTime");
static_assert(offsetof(FStruct_Ace_Passives_ChargeTime, ChargeTime_3_1FEB8B4040897739BAF5EBB2C45145E9) == 0x000000, "Member 'FStruct_Ace_Passives_ChargeTime::ChargeTime_3_1FEB8B4040897739BAF5EBB2C45145E9' has a wrong offset!");
static_assert(offsetof(FStruct_Ace_Passives_ChargeTime, ChargeDelay_6_5291777445E7D187DF9DE789A447A243) == 0x000004, "Member 'FStruct_Ace_Passives_ChargeTime::ChargeDelay_6_5291777445E7D187DF9DE789A447A243' has a wrong offset!");

}

