#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Struct_Larcin_PassivesBalancing

#include "Basic.hpp"

#include "DeceiveInc_structs.hpp"


namespace SDK
{

// ScriptStruct Struct_Larcin_PassivesBalancing.Struct_Larcin_PassivesBalancing
// 0x0018 (0x0018 - 0x0000)
struct FStruct_Larcin_PassivesBalancing final
{
public:
	TArray<EGameplayResourcesType>                StealPriorityList_3_FD8CA54C4806A11B40D764B679756178; // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	float                                         Mod1BroadcastDuration_7_1779F3AB4022A95FD6837D8E4F82C3D5; // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FStruct_Larcin_PassivesBalancing) == 0x000008, "Wrong alignment on FStruct_Larcin_PassivesBalancing");
static_assert(sizeof(FStruct_Larcin_PassivesBalancing) == 0x000018, "Wrong size on FStruct_Larcin_PassivesBalancing");
static_assert(offsetof(FStruct_Larcin_PassivesBalancing, StealPriorityList_3_FD8CA54C4806A11B40D764B679756178) == 0x000000, "Member 'FStruct_Larcin_PassivesBalancing::StealPriorityList_3_FD8CA54C4806A11B40D764B679756178' has a wrong offset!");
static_assert(offsetof(FStruct_Larcin_PassivesBalancing, Mod1BroadcastDuration_7_1779F3AB4022A95FD6837D8E4F82C3D5) == 0x000010, "Member 'FStruct_Larcin_PassivesBalancing::Mod1BroadcastDuration_7_1779F3AB4022A95FD6837D8E4F82C3D5' has a wrong offset!");

}

