#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Struct_Sasori_PassivesBalancing

#include "Basic.hpp"


namespace SDK
{

// ScriptStruct Struct_Sasori_PassivesBalancing.Struct_Sasori_PassivesBalancing
// 0x0008 (0x0008 - 0x0000)
struct FStruct_Sasori_PassivesBalancing final
{
public:
	float                                         Mod1DamageMultiplier_2_3CFA26C04065D53E473A18883524D2C2; // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Mod2CooldownRegain_5_5A8E7F0A45A6E1AE8270D6A28F89ACC6; // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FStruct_Sasori_PassivesBalancing) == 0x000004, "Wrong alignment on FStruct_Sasori_PassivesBalancing");
static_assert(sizeof(FStruct_Sasori_PassivesBalancing) == 0x000008, "Wrong size on FStruct_Sasori_PassivesBalancing");
static_assert(offsetof(FStruct_Sasori_PassivesBalancing, Mod1DamageMultiplier_2_3CFA26C04065D53E473A18883524D2C2) == 0x000000, "Member 'FStruct_Sasori_PassivesBalancing::Mod1DamageMultiplier_2_3CFA26C04065D53E473A18883524D2C2' has a wrong offset!");
static_assert(offsetof(FStruct_Sasori_PassivesBalancing, Mod2CooldownRegain_5_5A8E7F0A45A6E1AE8270D6A28F89ACC6) == 0x000004, "Member 'FStruct_Sasori_PassivesBalancing::Mod2CooldownRegain_5_5A8E7F0A45A6E1AE8270D6A28F89ACC6' has a wrong offset!");

}

