#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Struct_SpyShared_StatusEffectsBalancing

#include "Basic.hpp"


namespace SDK
{

// ScriptStruct Struct_SpyShared_StatusEffectsBalancing.Struct_SpyShared_StatusEffectsBalancing
// 0x0004 (0x0004 - 0x0000)
struct FStruct_SpyShared_StatusEffectsBalancing final
{
public:
	float                                         Value_4_3E50664948F52336395C2CB19A2E5E5C;          // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FStruct_SpyShared_StatusEffectsBalancing) == 0x000004, "Wrong alignment on FStruct_SpyShared_StatusEffectsBalancing");
static_assert(sizeof(FStruct_SpyShared_StatusEffectsBalancing) == 0x000004, "Wrong size on FStruct_SpyShared_StatusEffectsBalancing");
static_assert(offsetof(FStruct_SpyShared_StatusEffectsBalancing, Value_4_3E50664948F52336395C2CB19A2E5E5C) == 0x000000, "Member 'FStruct_SpyShared_StatusEffectsBalancing::Value_4_3E50664948F52336395C2CB19A2E5E5C' has a wrong offset!");

}

