#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TemaranWidgets

#include "Basic.hpp"


namespace SDK
{

// Enum TemaranWidgets.ET_InputDeviceType
// NumValues: 0x0004
enum class ET_InputDeviceType : uint8
{
	KBM                                      = 0,
	XBOX                                     = 1,
	PS                                       = 2,
	ET_MAX                                   = 3,
};

}

