#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TwAudio

#include "Basic.hpp"


namespace SDK::Params
{

// Function TwAudio.TwRTPCTrigger.ManuallySetSphereRadius
// 0x0004 (0x0004 - 0x0000)
struct TwRTPCTrigger_ManuallySetSphereRadius final
{
public:
	float                                         SetRadiusTo;                                       // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(TwRTPCTrigger_ManuallySetSphereRadius) == 0x000004, "Wrong alignment on TwRTPCTrigger_ManuallySetSphereRadius");
static_assert(sizeof(TwRTPCTrigger_ManuallySetSphereRadius) == 0x000004, "Wrong size on TwRTPCTrigger_ManuallySetSphereRadius");
static_assert(offsetof(TwRTPCTrigger_ManuallySetSphereRadius, SetRadiusTo) == 0x000000, "Member 'TwRTPCTrigger_ManuallySetSphereRadius::SetRadiusTo' has a wrong offset!");

}

